# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.srcs/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0.xci
# IP: The module: 'Module_top_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.gen/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.gen/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.gen/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.srcs/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0.xci
# IP: The module: 'Module_top_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.gen/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.gen/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.gen/sources_1/bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module_top_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
