# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_name.xdc

# Block Designs: bd/Module_top/Module_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module_top || ORIG_REF_NAME==Module_top} -quiet] -quiet

# IP: bd/Module_top/ip/Module_top_Module_read_par_ad76_0_0/Module_top_Module_read_par_ad76_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module_top_Module_read_par_ad76_0_0 || ORIG_REF_NAME==Module_top_Module_read_par_ad76_0_0} -quiet] -quiet

# IP: bd/Module_top/ip/Module_top_clk_wiz_0_0/Module_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module_top_clk_wiz_0_0 || ORIG_REF_NAME==Module_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Module_top/ip/Module_top_ila_0_0/Module_top_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module_top_ila_0_0 || ORIG_REF_NAME==Module_top_ila_0_0} -quiet] -quiet

# XDC: d:/GitHub_FPGA/AD7606/Parallel/Read_AD7606_Parallel_XC7A15T/Read_AD7606_Parallel_XC7A15T.gen/sources_1/bd/Module_top/Module_top_ooc.xdc
